### ISSUE TITLE
RSI custom period

### ISSUE THREAD

**Issue by hubov** [cinar/indicator#72]
Hi,

I develop a trading bot and I really appreciate your indicators library. I have found one thing missing for my strategy - the possibility of setting the period for RSI. It is fixed to 14 days like in the standard RSI strategy. Larry Connor developed the 2-period RSI strategy which I use in my trading strategy as well.

The solution requires a change to allow passing the period which is then used in RMA (Rolling Moving Average).

**Comment by cinar** [comment]
Hi!

Great to hear that you found the library useful. As you are developing a trading bot, if there are any other indicators that you are using, or would like to use, could you send me a list (message/bugs), so that I can try to add them to the library?

Yes, the current RSI function assumes 14 days period. With some indicators, I made the period as a parameter, and also provided a default one, but with the RSI, I didn't.   I think having that support would be great. I see that you already made the code changes, so thank you! I'll review and merge it now.

Best regards,

-onur
